version: "3.8"

services:
  app:
    build: .
    container_name: coexist-social-poster
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./json:/app/json
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  scheduler:
    build:
      context: ./scheduler-folder  # carpeta donde tienes scheduler.py y su Dockerfile
    container_name: coexist-scheduler
    depends_on:
      - app
