version: "3.8"

services:
  app:
    build: .
    container_name: social-poster
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./json:/app/json
    command: uvicorn main:app --host 0.0.0.0 --port 8000
